#!/bin/dash 

PATH="$PATH:$(pwd)"

test_dir="$(mktemp -d)"
cd "$test_dir" || exit 1

expected="$(mktemp)"
actual="$(mktemp)"

trap 'rm "$expected" "$actual" -rf "$test_dir"' INT HUP QUIT TERM EXIT

echo "test01"
echo line 1 > a
echo hello world >b
./pigs-add a b

cat > "$expected" <<EOF
Committed as commit 0
EOF

./pigs-commit -m 'first commit' > "$actual" > 2>&1

if ! diff "$expected" "$actual"
then
    echo "Test Failed"
    exit 1
fi
