#!/bin/sh

num_runs=5

for input_size in 100000
do
	for order in random sorted reverse 
	do
		for program in ./sortIntList "sort -n"
		do
			echo
			echo "Input size: $input_size, Order: $order, Program: $program"
			for i in $(seq 1 $num_runs)
			do
				case $order in
					random)
						seq $input_size | sort -R | /usr/bin/time -f "%U" $program > /dev/null
						;;
					sorted)
						seq $input_size | /usr/bin/time -f "%U" $program > /dev/null
						;;
					reverse)
						seq $input_size | sort -nr | /usr/bin/time -f "%U" $program > /dev/null
						;;
				esac
			done
		done
	done
done